# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

windowrule = float on, size (monitor_w*0.6) (monitor_h*0.7), match:class (org.qbittorrent.qBittorrent), match:title ^(?!qBittorrent v.*$).*$

windowrule = float on, size (monitor_w*0.6) (monitor_h*0.6), match:class (imv)

windowrule = opacity 0.90 0.80, float on, size (monitor_w*0.4) (monitor_h*0.65), match:class (pavucontrol)

windowrule = opacity 0.90 0.80, float on, match:class (blueman-manager)

windowrule = opacity 0.90 0.80, float on, match:class (nm-applet)

windowrule = opacity 0.90 0.80, float on, match:class (nm-connection-editor)

windowrule = opacity 0.90 0.80, float on, match:class (xfce-polkit)

windowrule = opacity 0.80, match:class (qt5ct)
windowrule = opacity 0.80, float on, match:class (qt6ct)
